Django/empleado/aplications/persona/urls.py
from django.urls import path
from . import views

app_name="persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),    
    path('listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
        ),
        
    path('listar-by-area/<shorname>/', 
        views.ListByArea.as_view(),
        name='empleados_area'
        ),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
            'ver-empleado/<pk>/',
            views.EmpleadoDetailView.as_view(),
            name='empleado_detail'
        ),
    path('add-empleado',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
        ),
    path(
        'succes',
        views.SuccesView.as_view(),
        name='correcto'
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),

    path('lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
        ),
    
    
   
]
  

Django/empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#from aplications.home.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplications.home.urls')),
    
    path('', include('aplications.persona.urls')),

    path('', include('aplications.departamento.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/empleado/aplications/persona/models.py
from email.mime import image
from django.db import models
from aplications.departamento.models import Departamento
from ckeditor.fields import RichTextField
# Create your models here.
class Habilidades(models.Model):
   habilidad = models.CharField('Habilidad', max_length=50)
   class meta:
     verbose_name='Habilidad'
     verbose_name_plural = 'Habilidades empleado'



   def __str__(self) :
        return str(self.id) + '-' + self.habilidad


class Empleado(models.Model):
    """Modelo para la tabla Empleado"""
    JOB_CHOISES=(
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('3', 'ECONOMISTA'),
        ('4', 'OTRO'),
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('apellidos', max_length=60)
    full_name= models.CharField('nombres completos', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOISES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True) 
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    class Meta:
     verbose_name='Mis empleados'
     verbose_name_plural = 'Mis colaboradores'
     ordering = ['last_name']
     #unique_together = ('name', 'shor_name')



    def __str__(self) :
        return str(self.id) + '-' + self.first_name + '-' + self.last_name 
    

        

Django/empleado/aplications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    

    class Meta:
        

        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
            )
        widgets={
            'habilidades': forms.CheckboxSelectMultiple()
        }

Django/empleado/aplications/persona/views.py
from typing import Any
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
    
)

from aplications import persona
#models
from .models import Empleado
#forms
from .forms import EmpleadoForm


class InicioView(TemplateView):
    """Vista que carga la pagina de inicio"""
    template_name = "inicio.html"


class ListAllEmpleados(ListView):
    template_name='persona/list_all.html'
    paginate_by= 4
    ordering='first_name'
    #model= Empleado
    context_object_name= 'empleados'
    def get_queryset(self):
        palabra_clave= self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave 
            #busca cadenas con similitudes (jo) lista todo lo que tenga dentro de la cadena jo
        )  
        return lista


class ListaEmpleadosAdmin(ListView):
    template_name='persona/lista_empleados.html'
    paginate_by= 10
    ordering='first_name'
    model= Empleado
    context_object_name= 'empleados'
       


class ListByArea(ListView):
    #lista empleados de un area
    template_name='persona/list_by_area.html'
    context_object_name='empleados'
   
    def get_queryset(self):
        area= self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__shor_name=area
        )
        return lista

class ListEmpleadosByKword(ListView):
        #Lista por palabra clave
        template_name = 'persona/by_kword.html'
        context_object_name= 'empleados'
        
        def get_queryset(self):
            print('***************************')
            palabra_clave= self.request.GET.get("kword", '')
            lista = Empleado.objects.filter(
            first_name=palabra_clave
        )
           
            return lista
        
class ListHabilidadesEmpleado(ListView):
     template_name= 'persona/habilidades.html'
     context_object_name= 'habilidades'
     def get_queryset(self):
        empleado= Empleado.objects.get(id=7)
        return empleado.habilidades.all()
     

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"
 
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo']= "empleado del mes"
        return context


class SuccesView(TemplateView):
    template_name = "persona/succes.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    form_class=EmpleadoForm
    #fields=['first_name','last_name','job']
    #fields=('__all__')#carga todos los campos del modelo
    """fields=[
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        'avatar'

    ] ya no porque se va a utilizar el form"""
    #success_url= '.'#para que se recargue la misma pagina
    success_url= reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        #logica del proceso
        empleado=form.save()
        empleado.full_name = empleado.first_name+ ' '+empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)
            


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields=[
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades'

    ]
    success_url= reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        #obtengo los datos de los campos
        self.object= self.get_object()
        print('****************METODO POST**************')
        print('****************************')
        print('========')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        #logica del proceso
        print('****************METODO form valid**************')
        print('****************************')
        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url= reverse_lazy('persona_app:empleados_admin')
             

Django/empleado/templates/persona/add.html
{% extends 'base.html' %}


{% block title %}
    Nuevo Empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar persona</h1>

        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="large-6 cell">
                <label>Nombres
                    {{form.first_name}}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Apellidos
                    {{form.last_name}}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Trabajo
                    {{form.job}}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Area
                    {{form.departamento}}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Habilidades Extra
                    {{form.habilidades}}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Foto
                    {{form.avatar}}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="submit success button">Agregar</button>
            </div>

            
            
        </form>

    </div>
</div>


{% endblock content %}
    

Django/empleado/templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}
    <input type="text"  id="kword" name="kword" placeholder="Ingrese el nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista Resultados</h3>
<ul>
    
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

Django/empleado/templates/persona/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar Empleados
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{object.first_name}}</h1>

        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout secondary">
                <h5>Desea eliminar este empleado?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>

    </div>
</div>

{% endblock content %}
    

Django/empleado/templates/persona/detail_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{object.first_name}} 
{% endblock title %}
  

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class=" cell large-4 card" style="width: 300px; margin-top: 10px;">
      <div class="card-divider">
        {{empleado.get_job_display}}
      </div>
      
      {% if empleado.avatar %}
        <img src="{{ empleado.avatar.url }}">
      {% else %}
        <img src="{% static 'img/imagen1.jpg' %}">
      {% endif %}
        
      
      <div class="card-section">
        <h4>{{empleado.full_name}}</h4>
        <p>{{empleado.first_name}}</p>
        <p>{{empleado.last_name}}</p>
        <p>{{empleado.departamento.shor_name}}</p>
        <p><span class="label">Habilidades:</span></p>
        <ul class="vertical menu">
          
          {% for h in empleado.habilidades.all %}
            <li>{{ h.habilidad }}</li>
          {% endfor %}
        </ul>
        
        
      </div>
    </div>

  </div>
</div>

{% endblock content %}

Django/empleado/templates/persona/habilidades.html
<h1>habilidades de empleado</h1>



<form method="GET">{% csrf_token %}
    <input type="text"  id="id" name="id" placeholder="Ingrese el id aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista Resultados</h3>
<ul>
    
    {% for h in habilidades %}
        <li>{{h}}</li>
    {% endfor %}

</ul>

Django/empleado/templates/persona/list_all.html
{% extends 'base.html' %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
    </div>
    <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
        <div class="cell large-7">
            <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
        </div>
        <div class="cell large-2">
            <button type="submit" class="submit success button">Buscar</button>
        </div>
    </form>
    <div class="cell">
        <table>
            <thead>
              <tr>
                <th width="200">ID</th>
                <th>NOMBRES</th>
                <th width="150">APELLIDOS</th>
                <th width="150">DEPARTAMENTO</th>
                <th width="150">ACCION</th>
              </tr>
            </thead>
            <tbody>
                {% for e in empleados %}
                <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                </tr>
                {% endfor %}
              
            </tbody>
        </table> 
    </div>
    <div class="cell">
        
        {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination">
              
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}" >Atras</a>
                </li>
                {% endif %}

                
                {% for pagina in paginator.page_range %}
                {% if page_obj.number == pagina %} 
                <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                {% else %}
                <li><a href="?page={{pagina}}" aria-label="Page {{ pagina }}">{{ pagina }}</a></li>    
                {% endif %}
                {% endfor %}
                    
                  

                {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{page_obj.next_page_number}}" >Siguiente</a>
                {% endif %}    
            </ul>
        </nav>  
        {% endif %}
            
        
    </div>

</div>




{% endblock content %}
    

Django/empleado/templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    lista empleados por departameno
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por Area</div>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                        <tr>
                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                        </tr>
                        {% endfor %}
                      
                    </tbody>
                </table> 
            </div>
        </div>

    </div>
{% endblock content %}
    
    
<h1>Lista de empleados por departamento</h1>


<ul>
    
    {% for e in object_list %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

Django/empleado/templates/persona/lista_empleados.html
{% extends 'base.html' %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
    </div>
    
    <div class="cell">
        <table>
            <thead>
              <tr>
                <th width="200">ID</th>
                <th>NOMBRES</th>
                <th width="150">APELLIDOS</th>
                <th width="150">DEPARTAMENTO</th>
                <th width="150">ACCION</th>
              </tr>
            </thead>
            <tbody>
                {% for e in empleados %}
                <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="button succes" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a></td>
                    <td><a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a></td>
                </tr>
                {% endfor %}
              
            </tbody>
        </table> 
    </div>
    <div class="cell">
        
        {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination">
              
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}" >Atras</a>
                </li>
                {% endif %}

                
                {% for pagina in paginator.page_range %}
                {% if page_obj.number == pagina %} 
                <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                {% else %}
                <li><a href="?page={{pagina}}" aria-label="Page {{ pagina }}">{{ pagina }}</a></li>    
                {% endif %}
                {% endfor %}
                    
                  

                {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{page_obj.next_page_number}}" >Siguiente</a>
                {% endif %}    
            </ul>
        </nav>  
        {% endif %}
            
        
    </div>

</div>




{% endblock content %}

Django/empleado/templates/persona/succes.html
<h1>felicitaciones se guardo correctamente el empleado</h1>

Django/empleado/templates/persona/update.html
{% extends 'base.html' %}


{% block title %}
    Editar Empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="large-6 cell">
                    <label>Nombres
                        {{form.first_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Apellidos
                        {{form.last_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Trabajo
                        {{form.job}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Area
                        {{form.departamento}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Habilidades Extra
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="submit success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}
    