Django/empleado/aplications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name= "departamento_app"

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path('departamento-lista/', 
        views.DepartamentoListView.as_view(), 
        name='departamento_list'
        ),

    
    
    
]

Django/empleado/aplications/persona/urls.py
from django.urls import path
from . import views

app_name="persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),    
    path('listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
        ),
        
    path('listar-by-area/<shorname>/', 
        views.ListByArea.as_view(),
        name='empleados_area'
        ),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
            'ver-empleado/<pk>/',
            views.EmpleadoDetailView.as_view(),
            name='empleado_detail'
        ),
    path('add-empleado',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
        ),
    path(
        'succes',
        views.SuccesView.as_view(),
        name='correcto'
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),

    path('lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
        ),
    
    
   
]
  

Django/empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#from aplications.home.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplications.home.urls')),
    
    path('', include('aplications.persona.urls')),

    path('', include('aplications.departamento.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/empleado/aplications/departamento/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)
    
    class Meta:
     verbose_name='Mi Departamento'
     verbose_name_plural = 'Areas de la Empresa'
     ordering = ['name']
     unique_together = ('name', 'shor_name')

    def __str__(self) :
        return str(self.id) + '-' + self.name + '-' + self.shor_name 

Django/empleado/aplications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField( max_length=50)
    apellidos = forms.CharField( max_length=50)
    departamento = forms.CharField( max_length=50)
    shorname = forms.CharField( max_length=50)

Django/empleado/aplications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView


from aplications import departamento
from aplications.persona.models import Empleado
from .models import Departamento

from .forms import NewDepartamentoForm

#from aplications import departamento
#from .models import Departamento



class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name='departamentos'



class NewDepartamentoView(FormView):
    template_name='departamento/new_departamento.html'
    
    form_class= NewDepartamentoForm
    success_url='/'

    def form_valid(self, form):
        depa= Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
            
        )
        depa.save()
        nombre=form.cleaned_data['nombre']
        apellido=form.cleaned_data['apellidos']

        Empleado.objects.create(
           first_name=nombre,
           last_name=apellido,
           job='1',
           departamento=depa
        )


        
        return super(NewDepartamentoView, self).form_valid(form)

        

Django/empleado/templates/departamento/lista.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{departamento.name}}</td>
                            <td>{{departamento.shor_name}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleados</a></td>
                        </tr>  
                        {% endfor %}
                            
                        
                    </tbody>
                </table>

            </div>
        </div>
    </div>

{% endblock content %}
    

Django/empleado/templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
    Nueva Area
{% endblock title %}
    

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Registrar nuevo departamento</h1>

        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="cell" >
                <h3>Datos Empleado</h3>
            </div>
            <div class="large-6 cell">
                <label>Nombres
                    {{form.nombre}}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Apellidos
                    {{form.apellidos}}
                </label>
            </div>
            <div class="cell" >
                <h3>Datos Departamento</h3>
            </div>
            <div class="large-6 cell">
                <label>Trabajo
                    {{form.departamento}}
                </label>
            </div>
            <div class="large-6 cell">
                <label>Area
                    {{form.shorname}}
                </label>
            </div>
            
            <div class="cell">
                <button type="submit" class="submit success button">Guardar</button>
            </div>
        
        </form>
        
    </div>

</div>

{% endblock content %}
    